### PUT Text Content ###
PUT http://localhost/api/obj/foo/bar2 HTTP/1.1
Content-Type: text/plain

< ../data/test.file

### PUT png image Content ###
PUT http://localhost/api/obj/foo/subfoo/bar3 HTTP/1.1
Content-Type: image/png

< ../data/Snipaste_test.png

### GET Text Content ###
GET http://localhost/api/obj/foo/bar2 HTTP/1.1
Content-Type: text/plain

### GET png image ###
GET http://localhost/api/obj/foo/bar3 HTTP/1.1
Content-Type: text/plain

### DELETE png image ###
DELETE  http://localhost/api/obj/foo/bar2 HTTP/1.1
Content-Type: text/plain

### GET object list ###
GET http://localhost/api/list/foo/1/2 HTTP/1.1
Content-Type: text/plain